import random
from urllib.request import urlopen
import sys

WORD_URL = "http://learncodethehardway.org/words.txt"
WORDS = []

PHRASES = {
    "class %%%(%%%):":
        "Make a class named %%% that is-a %%%.",
    "class %%%(object)\n\tdef __init__(self, ***)":
        "class %%%  has-a __init__ that takes self and *** params.",
    "class %%%(object):\n\tdef ***(self, @@@)":
        "class %%% has-a function *** that takes self and @@@ params.",
    "*** = %%%()":
        "Set *** to an instance of class %%%.",
    "***.***(@@@)":
        "From *** get the *** function and call it with params self and @@@",
    "***.*** = '***'":
        "From *** get the *** attribute and set it to '***'."
}

# do they want to drill phrases first - reverse translation
if len(sys.argv) == 2 and sys.argv[1] == "english":
    PHRASE_FIRST = True
else:
    PHRASE_FIRST = False

# load up the words from the website
for word in urlopen(WORD_URL).readlines():
    WORDS.append(str(word.strip(), encoding="utf-8"))\

# return str phrase to be translated
def convert(snippet, phrase):
    # capitalize the string list elements generated by random.sample
    # random.sample generates list of string randomly chosen from given WORDS list
    # and number of words given by counting "%%%" in each snippet
    class_names = [w.capitalize() for w in random.sample(WORDS, snippet.count("%%%"))] # interesting one
    other_names  = random.sample(WORDS, snippet.count("***"))
    results = []
    param_names = []

    for i in range(0, snippet.count("@@@")):
        # randomly choose the number of words
        param_count = random.randint(1,3)
        #randomly find the words and make a 1 string from them 
        param_names.append(', '.join(random.sample(WORDS, param_count)))

    # snippet, phrase is seen as a list with 2 elements
    for sentence in snippet, phrase:
        # this is how you duplicate a list or string
        # sentence[:] is a copy of sentence
        result = sentence[:]
    
         # fake class names
        for word in class_names:
            result = result.replace("%%%", word, 1)
            
        # fake other names
        for word in other_names:
            result = result.replace("***", word, 1)

        # fake parameter lists
        for word in  param_names:
            result = result.replace("@@@", word, 1)

        results.append(result)

    return results
    
# keep going until they hit CTRL-D
try:
    while True:
        # list of phrases
        snippets = list(PHRASES.keys())
        # reshuffle snippets
        random.shuffle(snippets)

        for snippet in snippets:
            phrase = PHRASES[snippet]
            # here we get snippers, and phrases fulfilled with object names
            question, answer = convert(snippet, phrase)
            if PHRASE_FIRST:
                # revers the varibales' names
                question, answer = answer, question

            print(question)

            input("> ")
            print(f"ANSWER: {answer}\n\n")
except EOFError:
    print("\nBye")

